name: Step 2, Skills Javascript

# This workflow runs when a skills.js file is pushed to the repository
on:
  workflow_dispatch:
  push:
    paths:
      - 'skills.js'
    branches:
      - main

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          if [[ -f ./.github/steps/-step.txt ]]; then
            echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "current_step=0" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_function_added:
    name: On function added
    needs: get_current_step
    if: ${{ needs.get_current_step.outputs.current_step == '2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check for skills.js file
        run: |
          if [[ -f skills.js ]]; then
            echo "skills.js file found"
          else
            echo "::error::The skills.js file was not found"
            exit 1
          fi
          
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
